import type { Account, PowerRole, ClaimRef, Product } from "./types";
const ref = (id: string, claim: string): ClaimRef => ({ id, claim });
const role = (
  title: string,
  controls: string,
  ask: string,
  stage: string,
  power: PowerRole["power"],
): PowerRole => ({ title, controls, ask, stage, power });
const acquisition = role(
  "SPB / DPB / DAC + Service HQ / MoD",
  "AoN, commercial process and delegated contract approvals",
  "Funded requirement and viable acquisition category",
  "AoN → RFP → negotiation → contract",
  [2, 2, 5, 2],
);
const design = role(
  "Indian prime / design authority",
  "Architecture, interfaces and subcontract selection",
  "An open integration interface and a named engineering owner",
  "Architecture → integration → acceptance",
  [3, 5, 2, 5],
);
export const accounts: Account[] = [
  {
    id: "army",
    name: "Indian Army",
    kind: "B2G",
    tier: 0,
    location: "New Delhi · field commands",
    platforms: "V-BAT; formation ISR; indigenous unmanned platforms",
    products: ["V-BAT", "Hivemind Enterprise", "Vision / ViDAR"],
    roles: [
      "DCOAS (CD&S)",
      "Army Design Bureau",
      "Army Aviation / ISR / Artillery directorates",
    ],
    constraint:
      "Current selection does not disclose expansion quantities or contract economics.",
    nextMove:
      "Deliver the current V-BAT programme well; convene ADB and selected partners around a sovereign Hivemind developer environment.",
    power: [5, 4, 4, 3],
    sources: [
      ref("india-contract", "Army V-BAT and SDK selection"),
      ref("army-roles", "DCOAS CD&S capability-development role"),
      ref("adb", "Industry / user facilitation"),
    ],
    chain: [
      role(
        "Field command / operational directorate",
        "Mission need and field validation",
        "A mission sponsor and agreed CONOPS",
        "Problem definition → field trials",
        [5, 3, 2.5, 2],
      ),
      role(
        "DCOAS (CD&S) + ADB",
        "Capability planning; ADB industry facilitation",
        "Requirements workshop and trial vehicle",
        "Requirement → technical evaluation",
        [4, 4, 4, 3],
      ),
      acquisition,
      design,
    ],
  },
  {
    id: "navy",
    name: "Indian Navy",
    kind: "B2G",
    tier: 1,
    location: "New Delhi · Mumbai · Visakhapatnam · Kochi",
    platforms: "NSUAS; autonomous surface craft; submersible vessels",
    products: [
      "V-BAT",
      "Vision / ViDAR",
      "Hivemind Solutions",
      "Aechelon",
      "Benchmark",
    ],
    roles: ["VCNS / DCNS", "ACNS (Air)", "NIIO / TDAC", "Chief of Materiel"],
    constraint:
      "AoN is an in-principle approval. Individual values and vendor selection are not disclosed.",
    nextMove:
      "Tie a V-BAT/ViDAR shipboard demonstration to NSUAS CONOPS; run a parallel NIIO/TDAC maritime autonomy workshop.",
    power: [5, 4, 4, 3],
    sources: [
      ref("dac-july", "NSUAS AoN"),
      ref("dac-aug25", "Compact autonomous surface craft AoN"),
      ref("dac-july25", "Submersible autonomous vessel AoN"),
      ref("niio", "Innovation entry route"),
    ],
    chain: [
      role(
        "Commands + naval warfare / aviation user",
        "Maritime CONOPS and operational trials",
        "Ship access and a defined ISR mission",
        "User need → sea trials",
        [5, 3, 2, 2],
      ),
      role(
        "VCNS / ACNS (Air) + NIIO / TDAC",
        "Capability / aviation integration; innovation entry",
        "A trial sponsor and integration requirements",
        "Requirement → prototype → technical trials",
        [4, 4, 3, 4],
      ),
      acquisition,
      design,
    ],
  },
  {
    id: "iaf",
    name: "Indian Air Force",
    kind: "B2G",
    tier: 1,
    location: "New Delhi · Bengaluru",
    platforms: "HAPS; MALE; unmanned teaming; training / T&E",
    products: ["Hivemind Enterprise", "Aechelon", "Benchmark", "X-BAT"],
    roles: ["DCAS", "ASTE", "Training Command"],
    constraint:
      "Test, training and requirement organisations have different remits. No disclosed Indian CCA software budget.",
    nextMove:
      "Propose a Hivemind Enterprise / Aechelon evaluation workflow with ASTE, DRDO and HAL before fleet-scale procurement.",
    power: [5, 5, 4, 3],
    sources: [
      ref("dac-july", "IAF fixed-wing HAPS AoN"),
      ref("male-it", "Reported tri-service MALE with IAF lead"),
      ref("drdo-aero", "Aeronautical R&D ecosystem"),
    ],
    chain: [
      role(
        "Air operations / Training Command",
        "Operational need or pilot readiness",
        "A use case and baseline performance metrics",
        "Need → training pilot",
        [5, 3, 2, 2],
      ),
      role(
        "DCAS + ASTE / relevant technical branch",
        "Capability requirements and flight-test evaluation",
        "A test plan and technical acceptance criteria",
        "Requirements → T&E",
        [4, 5, 3, 3],
      ),
      acquisition,
      design,
    ],
  },
  {
    id: "icg",
    name: "Indian Coast Guard",
    kind: "B2G",
    tier: 2,
    location: "New Delhi · maritime regions",
    platforms: "OPV / patrol-vessel maritime ISR",
    products: ["V-BAT", "Vision / ViDAR", "Aechelon", "Benchmark"],
    roles: [
      "Operations directorate",
      "Aviation authorities",
      "Regional commanders",
    ],
    constraint:
      "Defence / maritime-security adjacency; no disclosed V-BAT selection.",
    nextMove:
      "Secure a patrol-vessel ISR pilot sponsor and test deck operations plus automated detection.",
    power: [5, 4, 3, 2],
    sources: [
      ref("icg-budget", "Coast Guard defence budget context"),
      ref("vbat", "Ship-capable VTOL product"),
    ],
    chain: [
      role(
        "Regional command / vessel user",
        "Patrol ISR problem",
        "A pilot vessel and mission baseline",
        "CONOPS → demonstration",
        [5, 3, 2, 2],
      ),
      role(
        "HQ aviation / technical authority",
        "Flight and ship integration approval",
        "Defined deck and sensor trial criteria",
        "Integration → trials",
        [4, 4, 2, 3],
      ),
      acquisition,
      design,
    ],
  },
  {
    id: "drdo",
    name: "DRDO / defence R&D",
    kind: "B2G",
    tier: 1,
    location: "New Delhi · Bengaluru · Visakhapatnam",
    platforms: "ADE / CABS unmanned air systems; NSTL underwater autonomy",
    products: ["Hivemind Enterprise", "Aechelon", "Vision / ViDAR"],
    roles: [
      "DG Aeronautical Systems",
      "ADE / CABS programme leadership",
      "CEMILAC",
      "NSTL",
    ],
    constraint:
      "Indian R&D retains programme ownership; airworthiness is a separate gate. Exact programme access requires diligence.",
    nextMove:
      "Frame Enterprise as a sovereign development and validation accelerator; identify a lab-owned test platform.",
    power: [3, 5, 2, 4],
    sources: [
      ref("drdo-aero", "Aeronautical R&D cluster"),
      ref("nstl", "Underwater autonomy technology context"),
    ],
    chain: [
      role(
        "Service sponsor + lab programme team",
        "Military need and R&D mission",
        "A service-backed problem statement",
        "R&D definition",
        [4, 4, 2, 3],
      ),
      role(
        "ADE / CABS / NSTL + certification authority",
        "Design, validation and certification",
        "Data interfaces and verification criteria",
        "R&D → certification",
        [3, 5, 2, 5],
      ),
      role(
        "Lab / DRDO + service financial chain",
        "Project and delegated funding",
        "Identify the actual funding route",
        "Sanction → contract",
        [2, 3, 4, 2],
      ),
      design,
    ],
  },
  {
    id: "dsa",
    name: "DSA / HQ IDS / NSCS",
    kind: "B2G",
    tier: 3,
    location: "New Delhi · military space ecosystem",
    platforms: "SBS-III surveillance constellation",
    products: ["Hivemind Enterprise", "Hivemind Solutions", "Aechelon"],
    roles: [
      "DSA capability / mission leadership",
      "HQ IDS",
      "Programme technical authority",
    ],
    constraint:
      "Reported programme structure; third-party software architecture and procurement access are unknown.",
    nextMove:
      "Use NOVI to discuss constellation tasking and health constraints; establish whether a third-party autonomy layer is permitted.",
    power: [4, 4, 3, 2],
    sources: [
      ref("sbs", "Reported SBS-III context and oversight"),
      ref("novi", "Satellite autonomy capability proof"),
    ],
    chain: [
      role(
        "DSA / IDS mission sponsor",
        "Military surveillance mission",
        "Validate autonomy need",
        "Concept shaping",
        [5, 3, 2, 2],
      ),
      role(
        "Programme / satellite technical authority",
        "Flight software and constellation architecture",
        "Confirm third-party software access",
        "Architecture review",
        [3, 5, 2, 5],
      ),
      role(
        "Programme sanction / financial authority · confirm",
        "SBS-III programme funding; specific route unverified",
        "Identify responsible authority; do not infer standard DAP chain",
        "Programme diligence",
        [2, 3, 4, 2],
      ),
      role(
        "Satellite builder / design authority",
        "Onboard integration and subcontractors",
        "A qualified interface and test path",
        "Integration → validation",
        [3, 5, 2, 5],
      ),
    ],
  },
];
type OEMSeed = [
  string,
  string,
  0 | 1 | 2,
  string,
  string,
  Product[],
  string[],
  string,
  string,
  [number, number, number, number],
  string,
];
const oems: OEMSeed[] = [
  [
    "jsw",
    "JSW Defence",
    0,
    "Hyderabad · India programme route",
    "V-BAT manufacturing, training and MRO",
    ["V-BAT", "Hivemind Enterprise"],
    [
      "India programme leadership",
      "Manufacturing / supply chain",
      "Training & sustainment",
    ],
    "Local manufacturing, licensing and partner economics are not public.",
    "Agree delivery readiness, local supply-chain milestones and a joint service expansion plan.",
    [3, 4, 2, 5],
    "india-contract",
  ],
  [
    "hal",
    "HAL",
    1,
    "Bengaluru · New Delhi",
    "CATS Warrior / Alfa / Hunter / Infinity; 5-tonne HALE",
    ["Hivemind Enterprise", "Hivemind Solutions", "Aechelon", "X-BAT"],
    [
      "Platform programme director",
      "Mission & Combat Systems / avionics",
      "Planning & Projects",
      "Corporate Marketing, New Delhi",
    ],
    "Indigenous architecture ownership is essential; incumbent mission-autonomy selection is not established.",
    "Secure a CATS/HAPS architecture workshop. Use MHI proof to propose a 60–90-day Enterprise integration on an available test vehicle.",
    [4, 5, 2, 5],
    "hal",
  ],
  [
    "bel",
    "BEL",
    1,
    "Bengaluru",
    "Unmanned UAV / UGV / UUV / USV family; counter-UAS",
    ["Hivemind Enterprise", "Tracker C-UAS", "Vision / ViDAR"],
    [
      "Unmanned Systems vertical",
      "R&D / systems engineering",
      "Strategic Planning / Marketing",
    ],
    "Strong internal capability. The BEL-hosted portfolio confirms a partner ecosystem; verify the current architecture and partnership remit.",
    "Run a mission-autonomy / Tracker workshop and identify one UAV, USV or counter-UAS demonstrator.",
    [3, 5, 2, 5],
    "bel",
  ],
  [
    "newspace",
    "NewSpace Research & Technologies",
    1,
    "Bengaluru",
    "Heterogeneous UAVs; brief-supplied Beluga / Nimbus / Mackerel family names to confirm",
    ["Hivemind Enterprise", "Hivemind Solutions"],
    [
      "Platform programme leadership",
      "Autonomy engineering",
      "Defence business development",
    ],
    "Own autonomy IP; willingness to adopt external tooling and current legacy product-family availability are unconfirmed.",
    "Propose a Catalyst-style trial for heterogeneous teaming and dynamic retasking on one platform family.",
    [4, 5, 1, 5],
    "newspace",
  ],
  [
    "grse",
    "GRSE",
    1,
    "Kolkata",
    "Swadheen USV / ASV MCM; autonomous underwater R&D",
    ["Hivemind Solutions", "Aechelon", "Vision / ViDAR"],
    [
      "R&D / autonomous systems",
      "Naval programme director",
      "Design authority",
    ],
    "A platform signal does not establish an open autonomy architecture or Shield selection.",
    "Propose one USV ISR or ASW-support demonstrator, using Thunder Tiger as capability proof before multi-asset teaming.",
    [4, 5, 2, 5],
    "grse",
  ],
  [
    "tasl",
    "Tata Advanced Systems",
    1,
    "Hyderabad · New Delhi",
    "Sky-I; Rakshak VTOL; Advanced Loitering Systems",
    ["Hivemind Enterprise", "Hivemind Solutions", "Vision / ViDAR"],
    [
      "Unmanned systems programme director",
      "Mission software / systems engineering",
      "Business development",
    ],
    "Own autopilot, GCS and mission software. Incremental value must exceed existing autonomy.",
    "Scope contested-environment mission autonomy and teaming above the existing autopilot; agree a measurable integration trial.",
    [4, 5, 2, 5],
    "tasl",
  ],
  [
    "bdl",
    "BDL",
    1,
    "Hyderabad · Visakhapatnam",
    "Missiles / underwater weapons; Jishnu",
    ["Hivemind Solutions", "Vision / ViDAR"],
    [
      "Product programme director",
      "R&D / systems engineering",
      "DRDO programme liaison",
    ],
    "DRDO and service gates govern weapons integration; no assumption of terminal seeker or guidance-IP control.",
    "Define a collaborative mission-behaviour evaluation with BDL, DRDO and the user; clarify design rights before integration.",
    [3, 4, 2, 4],
    "bdl",
  ],
  [
    "adani",
    "Adani Defence & Aerospace",
    2,
    "Hyderabad · Kanpur · Gwalior",
    "Drishti 10 MALE; other indigenous UAV families",
    ["Hivemind Solutions", "Vision / ViDAR"],
    ["UAV programme director", "Mission systems lead"],
    "Drishti has an Elbit-derived technology architecture; low openness unless the user requires a separate software layer.",
    "Ask about open perception interfaces or future indigenous systems; qualify the architecture before pursuing an autonomy replacement.",
    [3, 4, 2, 4],
    "adani",
  ],
  [
    "lt",
    "L&T Precision Engineering & Systems",
    2,
    "Mumbai · Bengaluru · Talegaon · Kattupalli",
    "87-MALE with GA-ASI; naval / subsea systems",
    ["Hivemind Solutions", "Aechelon"],
    ["Unmanned systems programme leadership", "Naval systems engineering"],
    "GA-ASI MALE and Exail MCM partnerships constrain entry; an open future programme needs separate qualification.",
    "Target an open architecture outside incumbent-controlled MALE and MCM work; validate sensor or simulation interfaces.",
    [4, 5, 2, 5],
    "lt",
  ],
  [
    "mdl",
    "Mazagon Dock Shipbuilders",
    2,
    "Mumbai",
    "AUV / swarm AUV / autonomous tug R&D",
    ["Hivemind Solutions", "Aechelon"],
    ["R&D leadership", "Autonomous systems design authority"],
    "R&D disclosure is not a funded software procurement; verify programme and design opening.",
    "Confirm one active underwater autonomy programme and its simulation / mission-software integration gap.",
    [3, 5, 2, 5],
    "mdl",
  ],
  [
    "kalyani",
    "Kalyani / Bharat Forge",
    2,
    "Pune · Talegaon ecosystem",
    "Weapons / maritime autonomy · diligence target",
    ["Hivemind Solutions"],
    ["Defence systems programme director", "R&D / design leadership"],
    "Included as a brief-supplied ecosystem lead only. Specific platform ownership and partner rights are unverified.",
    "Qualify an Indian-owned defence platform and programme sponsor before creating an opportunity cell.",
    [3, 4, 1, 4],
    "",
  ],
  [
    "sagar",
    "Sagar Defence Engineering",
    2,
    "Maritime systems ecosystem · location to verify",
    "Military autonomous surface systems · diligence target",
    ["Hivemind Solutions"],
    ["Defence programme leadership", "Autonomy integration lead"],
    "No active platform or buyer verified in this implementation; excluded from opportunity cells and totals.",
    "Verify a named active military platform, buyer and integration authority before pursuit.",
    [3, 4, 1, 4],
    "",
  ],
];
accounts.push(
  ...oems.map(
    ([
      id,
      name,
      tier,
      location,
      platforms,
      products,
      roles,
      constraint,
      nextMove,
      power,
      source,
    ]) => ({
      id,
      name,
      kind: "B2B" as const,
      tier,
      location,
      platforms,
      products,
      roles,
      constraint,
      nextMove,
      power,
      sources: source
        ? [
            ref(source, platforms),
            ...(id === "newspace"
              ? [
                  ref(
                    "newspace-swarm",
                    "Official heterogeneous fixed-wing swarm demonstration",
                  ),
                ]
              : id === "adani"
                ? [
                    ref(
                      "adani-elbit",
                      "Existing Adani / Elbit manufacturing relationship",
                    ),
                  ]
                : id === "lt"
                  ? [ref("lt-exail", "Exail MCM partnership")]
                  : id === "grse"
                    ? [
                        ref(
                          "grse-filing",
                          "Swadheen 5m USV for Indian Navy needs",
                        ),
                      ]
                    : []),
          ]
        : [],
    }),
  ),
);
export const accountById = Object.fromEntries(accounts.map((a) => [a.id, a]));
